title: My Learning Journey
description: A walkthrough and result of my learning experience
show_downloads: false
google_analytics: G-MKQK789F6L
theme: jekyll-theme-primer

markdown: kramdown

github:
  is_project_page: false
  
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
